name: Firebase Prod Deployment
on: 
  push:
    branches: [ master ]

jobs:
  deploy: 
    name: Deployment to Firebase
    if: github.repository == 'opensandiego/sdvv-frontend'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - uses: actions/setup-python@v2
        with: 
          python-version: '3.x'

      - name: Cache pip
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
            
      - name: Install Python dependencies
        run: pip install -r requirements.txt
        
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm ci

      - name: Updating csv and json data 

      - name: Building
        run: npm run build

      - name: Deploying to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --project=production
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_PROD }}
