name: End-to-end tests
on: 
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  cypress-run-browser:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [ chrome ]
    name: E2E on ${{matrix.browser}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          build: npm run build:lib
          start: npm run start:db:staging
          wait-on: 'http://localhost:4200'
          browser: ${{matrix.browser}}
          headless: true
          # spec: cypress/e2e/sdvv-frontend.cy.js
          config-file: cypress.config.ts
      # - name: Upload Screenshots (if generated)
      #   uses: actions/upload-artifact@v1
      #   if: failure()
      #   with:
      #     name: cypress-screenshots
      #     path: cypress/screenshots
      # - name: Upload Video
      #   uses: actions/upload-artifact@v1
      #   if: always()
      #   with:
      #     name: cypress-videos
      #     path: cypress/videos
          
